services:
  pwa-canal-local:
    build: .
    container_name: canal_nostalgia_pwa
    restart: unless-stopped
    ports:
      # ANTES: - "3001:3000"
      # DEPOIS (CORRETO):
      - "0.0.0.0:3001:3000"
    environment:
      - PUBLIC_SERVER_URL=http://100.89.81.37:3000
